language: python
cache:
  pip: true
  directories:
    - node_modules
python:
  - 3.6
services:
  - docker
before_install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install 10.9
install:
  - pip install -r requirements.txt
  - npm install .
script:
  - set -e
  - chmod +x ./scripts/build.sh && ./scripts/build.sh
  - mkdocs build -v
  - find ./site -type f -name '*.html' -exec node --max_old_space_size=512 ./scripts/render_math.js {} \;
  - npx gulp minify
  - python scripts/gen_redirect.py
  - set +e
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GH_TOKEN
  local-dir: site
  on:
    branch: master
after_deploy:
  - chmod +x scripts/BaiduPusher.sh && ./scripts/BaiduPusher.sh
  - find ./ -type f -name "*.html" -exec sed -i -E 's/([^"]*)(assets[^"]*)/https:\/\/cdn-for-oi-wiki.billchn.com\/\2/g' {} +

