# Project Information
site_name: OI Wiki
site_description: OI Wiki
site_author: OI Wiki Team
site_url: https://oi-wiki.cf

# Repository
repo_name: 'Ir1d/OI-wiki'
repo_url: 'https://github.com/Ir1d/OI-wiki'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2016 - 2018 OI Wiki Team'

# Contents
pages:
  - Introduction:
    - Getting Started: index.md
    - OI 历史: introduction/history.md
    - OI 竞赛赛制简介: introduction/mode.md
    - 学习资源: introduction/resources.md
  - Basic:
    - Getting Started: basic/index.md
  - Dynamic Programming:
    - Getting Started: dp/index.md
  - String:
    - Getting Started: string/index.md
  - Math:
    - Getting Started: math/index.md
  - Data Structure:
    - Getting Started: data-structure/index.md
  - Graph:
    - Getting Started: graph/index.md
  - Geometry:
    - Getting Started: geometry/index.md
  - Misc:
    - Getting Started: misc/index.md

# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  logo:
    icon: 'school'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# Customization
extra:
  search:
    language: 'cn'

extra_javascript:
  - '_static/js/extra.js'
  - 'https://cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - '_static/css/extra.css'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
