blank_issues_enabled: false
contact_links:
  - name: 加入我们的 QQ 群组
    url: https://jq.qq.com/?_wv=1027&k=5EfkM6K 
    about: 加入我们的 QQ 群组来获取更多更新！
  - name: 加入我们的 Telegram 群组
    url: https://t.me/OIwiki
    about: 加入我们的 Telegram 群组来获取更快的响应！
  - name: 查看我们的 F.A.Q.
    url: https://oi-wiki.org/intro/faq/
    about: 提问之前先阅读一下 F.A.Q. 和规则哦~
